### ISSUE TITLE
Microservice

### ISSUE THREAD

**Issue by amitkumarj441** [xrayhunter/Docker-Flask-PostgreSQL-microservice#1]
Here is a basic microservice architecture based on https://www.npmjs.com/package/omg:

```
omg: 1
lifecycle:
  startup:
    command: ["python", "/app/app.py"]
actions:
  exec:
    help: Run a SELECT statement
    http:
      path: /execute
      port: 8000
      method: post
      contentType: application/json
    arguments:
      query:
        help: The query
        required: true
        in: requestBody
        type: string
      data:
        help: |
          If your query contains named parameters, such as
          SELECT * from my_table where name=%(username)s
          then specify "data" as {"name": "foo"}.
        required: false
        in: requestBody
        type: map

environment:
  POSTGRES_DSN:
    help: The DSN to connect to PostgresSQL.
    type: string
```

Also, follow the above architecture and ping me on PostgreSQL slack channel.
